### ISSUE TITLE
编码问题

### ISSUE THREAD

**Issue by nothingrealhappen** [0x5e/wechat-deleted-friends#1]
```
Traceback (most recent call last):
  File "wdf.py", line 452, in <module>
    main()
  File "wdf.py", line 375, in main
    MemberList = webwxgetcontact()
  File "wdf.py", line 214, in webwxgetcontact
    dic = json.loads(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x85 in position 63: invalid start byte
```

**Comment by nothingrealhappen** [comment]
原因是我关注了一个公众号  json 里看到有乱码  应该是不能解析的特殊符号之类的

取消关注就好了

**Comment by 0x5e** [comment]
嗯,这个好像也没有什么好的解决方法..先这样吧,谢谢了

**Comment by tianyusasori** [comment]
额，windows 下面还是编码有问题，命令行查看chcp是936，但是运行程序会报UnicodeDecodeError: 'utf8' codec can't decode byte 0xc4 in position 0: invalid continuation byte 的错误。不知道怎么解决。。

#15：13更新  已经解决啦~

**Comment by wy193777** [comment]
不知为何，win10 下输出的中文全是乱码。难道是因为我是英文版系统？
