### ISSUE TITLE
用不了啊 ，Mac python2.7环境

### ISSUE THREAD

**Issue by zb188** [0x5e/wechat-deleted-friends#124]
程序的查询结果可能会引起一些心理上的不适,请小心使用...
1小时内只能使用一次，否则会因操作繁忙阻止建群
Traceback (most recent call last):
  File "wdf.py", line 568, in <module>
    main()
  File "wdf.py", line 448, in main
    if not getUUID():
  File "wdf.py", line 76, in getUUID
    r= myRequests.get(url=url, params=params)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, *_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: /jslogin?fun=new&lang=zh_CN&_=1457921821&appid=wx782c26e4c19acffb (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x103741e50>: Failed to establish a new connection: [Errno 61] Connection refused',)))

**Comment by angerhang** [comment]
你可能忘记装request了
在terminal里

``` shell
$ sudo easy_install pip # 安装pip
$ pip install requests
```
