### ISSUE TITLE
AttributeError: 'module' object has no attribute '_create_unverified_context'

### ISSUE THREAD

**Issue by xo0** [0x5e/wechat-deleted-friends#127]
本程序的查询结果可能会引起一些心理上的不适,请小心使用...
1小时内只能使用一次，否则会因操作繁忙阻止建群
Traceback (most recent call last):
  File "wdf.py", line 568, in <module>
    main()
  File "wdf.py", line 442, in main
    ssl._create_default_https_context = ssl._create_unverified_context
AttributeError: 'module' object has no attribute '_create_unverified_context'

windows  不会    ubuntu会

**Comment by cato1718** [comment]
讲道理的话，可以用python3打开试试

**Comment by zackz-woolloo** [comment]
SSLContext was introduced in 2.7.9, you're using an old version of Python so it doesn't have this attribute.
