### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by hxzqlh** [0x5e/wechat-deleted-friends#136]
扫描二维码后出现的错误：

```
Allen@MacBook-Pro:~/workspace/wechat-deleted-friends$ git pull

remote: Counting objects: 48, done.
remote: Total 48 (delta 20), reused 20 (delta 20), pack-reused 28
Unpacking objects: 100% (48/48), done.
From https://github.com/0x5e/wechat-deleted-friends
   b13681c..eb72438  master     -> origin/master
Updating b13681c..eb72438
Fast-forward
 README.md |   4 +++
 wdf.py    | 186 +++++++++++++++++++++++++++++++++++++++++++++++++-------------------------------------------------------------
 2 files changed, 86 insertions(+), 104 deletions(-)
Allen@MacBook-Pro:~/workspace/wechat-deleted-friends$ python wdf.py
本程序的查询结果可能会引起一些心理上的不适,请小心使用...
1小时内只能使用一次，否则会因操作繁忙阻止建群
正在获取二维码图片...
请使用微信扫描二维码以登录
成功扫描,请在手机上点击确认以登录
Traceback (most recent call last):
  File "wdf.py", line 570, in <module>
    main()
  File "wdf.py", line 457, in main
    while waitForLogin() != '200':
  File "wdf.py", line 139, in waitForLogin
    code = pm.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by iliul** [comment]
这是正则没有匹配到，我试了下我这里可以的，你再试试呢？
