### ISSUE TITLE
检测出问题

### ISSUE THREAD

**Issue by SuperDannyBoy** [0x5e/wechat-deleted-friends#144]
Traceback (most recent call last):
  File "/Users/superdanny/Downloads/wechat-deleted-friends-master/wdf.py", line 570, in <module>
    main()
  File "/Users/superdanny/Downloads/wechat-deleted-friends-master/wdf.py", line 498, in main
    (DeletedList, BlockedList) = addMember(ChatRoomName, UserNames)
  File "/Users/superdanny/Downloads/wechat-deleted-friends-master/wdf.py", line 351, in addMember
    r = myRequests.post(url=url, data=json.dumps(params),headers=headers)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 514, in post
    return self.request('POST', url, data=data, json=json, *_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 471, in request
    resp = self.send(prep, *_send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 581, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(54, 'Connection reset by peer'))

**Comment by h1048576** [comment]
貌似已经不能用了
