### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by Han40** [0x5e/wechat-deleted-friends#156]
Traceback (most recent call last):
  File "wdf.py", line 570, in <module>
    main()
  File "wdf.py", line 496, in main
    UserNames)
  File "wdf.py", line 299, in createChatroom
    data = r.json()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by xumeng723** [comment]
I met the same question as you

**Comment by Corbusier** [comment]
一模一样的提示...不知道这是什么意思

**Comment by Han40** [comment]
怎么搞搞？？？

**Comment by XieJiSS** [comment]
这是因为微信网页版删除了
```
https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxcreatechatroom
```
现在网页版好像不能创建群聊了
