### ISSUE TITLE
Mac Pro 10.11.1 报错.

### ISSUE THREAD

**Issue by YixuanFranco** [0x5e/wechat-deleted-friends#17]
请使用微信扫描二维码以登录
成功扫描,请在手机上点击确认以登录
正在登录...
Traceback (most recent call last):
  File "wdf.py", line 433, in <module>
    main()
  File "wdf.py", line 355, in main
    MemberList = webwxgetcontact()
  File "wdf.py", line 223, in webwxgetcontact
    dic = json.loads(data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9f in position 2: invalid start byte

**Comment by 0x5e** [comment]
https://github.com/0x5e/wechat-deleted-friends/issues/1 可能和这个是同一个问题,有人的昵称里有特殊的编码?可否DEBUG改为True,运行看一下根目录webwxgetcontact.json文件,是什么样的字符
