### ISSUE TITLE
win10 python版本2.7.10 扫面完后报错

### ISSUE THREAD

**Issue by yangblink** [0x5e/wechat-deleted-friends#21]
win10 python版本`2.7.10` 扫面完后报错

```
Traceback (most recent call last):
  File "wdf.py", line 433, in <module>
    main()
  File "wdf.py", line 393, in main
    deleteMember(ChatRoomName, UserNames)
  File "wdf.py", line 286, in deleteMember
    response = urllib2.urlopen(request)
  File "c:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "c:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "c:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "c:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "c:\Python27\lib\urllib2.py", line 1240, in https_open
    context=self._context)
  File "c:\Python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:590)>
```

**Comment by 0x5e** [comment]
应该是网络问题,没有异常处理,先多试几次吧

**Comment by poorly** [comment]
Please stop emailing me

**Comment by yangblink** [comment]
用git bash比较容易出现这个问题，换成cmd就好了。
