### ISSUE TITLE
停滞在了"回车键继续..."

### ISSUE THREAD

**Issue by Razeen** [0x5e/wechat-deleted-friends#23]
在回车键继续之后就没有下文了。
用的是python 2.7.5
Ubuntu 和 Mac 都没有反应

**Comment by Razeen** [comment]
^CTraceback (most recent call last):

  File "wdf.py", line 433, in <module>

```
main()
```

  File "wdf.py", line 339, in main

```
showQRImage()
```

  File "wdf.py", line 76, in showQRImage

```
response = urllib2.urlopen(request)
```

  File "/usr/local/lib/python2.7/urllib2.py", line 127, in urlopen

```
return _opener.open(url, data, timeout)
```

  File "/usr/local/lib/python2.7/urllib2.py", line 404, in open

```
response = self._open(req, data)
```

  File "/usr/local/lib/python2.7/urllib2.py", line 422, in _open

```
'_open', req)
```

  File "/usr/local/lib/python2.7/urllib2.py", line 382, in _call_chain

```
result = func(*args)
```

  File "/usr/local/lib/python2.7/urllib2.py", line 1222, in https_open

```
return self.do_open(httplib.HTTPSConnection, req)
```

  File "/usr/local/lib/python2.7/urllib2.py", line 1181, in do_open

```
h.request(req.get_method(), req.get_selector(), req.data, headers)
```

  File "/usr/local/lib/python2.7/httplib.py", line 973, in request

```
self._send_request(method, url, body, headers)
```

  File "/usr/local/lib/python2.7/httplib.py", line 1007, in _send_request

```
self.endheaders(body)
```

  File "/usr/local/lib/python2.7/httplib.py", line 969, in endheaders

```
self._send_output(message_body)
```

  File "/usr/local/lib/python2.7/httplib.py", line 829, in _send_output

```
self.send(msg)
```

  File "/usr/local/lib/python2.7/httplib.py", line 791, in send

```
self.connect()
```

  File "/usr/local/lib/python2.7/httplib.py", line 1172, in connect

```
self.timeout, self.source_address)
```

  File "/usr/local/lib/python2.7/socket.py", line 562, in create_connection

```
sock.connect(sa)
```

  File "/usr/local/lib/python2.7/socket.py", line 224, in meth

```
return getattr(self._sock,name)(*args)
```

KeyboardInterrupt

**Comment by Razeen** [comment]
网络连接问题。。。
