### ISSUE TITLE
看到了您的代码，非常想学习python

### ISSUE THREAD

**Issue by earyantLe** [0x5e/wechat-deleted-friends#38]
您好，看到了您的代码，非常想学习python，我没有任何python的经验，问您一下出现一下状况：
  File "wdf.py", line 91
    print '请使用微信扫描二维码以登录'
                        ^
SyntaxError: Missing parentheses in call to 'print'
麻烦您回复一下，谢谢您！！

**Comment by tonicmuroq** [comment]
用  python 2.7 吧

**Comment by yuanfanggo** [comment]
Traceback (most recent call last):
  File "wdf.py", line 429, in <module>
    print '本程序的查询结果可能会引起一些心理上的不适,请小心使用...'
  File "wdf.py", line 420, in write
    s = s.decode('utf-8')
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb1 in position 0: invalid s
tart byte

？？我的是2.7的

**Comment by earyantLe** [comment]
Traceback (most recent call last):
  File "wdf.py", line 429, in <module>
    print '鏈▼搴忕殑鏌ヨ缁撴灉鍙兘浼氬紩璧蜂竴浜涘績鐞嗕笂鐨勪笉閫?璇峰皬蹇冧娇鐢?..'
  您好，换了版本后出现这样的状况：
File "wdf.py", line 422, in write
    self.target.write(s)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-20: ordinal not in range(128)
编码问题也查看了您在上面给出的csdn网址，可是import之后还是这样

**Comment by LesterLyu** [comment]
把encoding调成utf-8

**Comment by tonicmuroq** [comment]
其实 readme 不是写了 Mac 直接跑么... windows 得改下编码
