### ISSUE TITLE
win7跑完出结果后有报错

### ISSUE THREAD

**Issue by bambooom** [0x5e/wechat-deleted-friends#61]
git bash + python 2.7.10

```
 Everything is OK当前,你被0人删除,好友共258人
 Traceback (most recent call last):好友共258人
  File "wdf.py", line 485, in <module>
    main()
  File "wdf.py", line 429, in main
    DeletedList = addMember(ChatRoomName, UserNames)
  File "wdf.py", line 359, in addMember
    print(ErrMsg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-11: ordinal not in range(128)
```

**Comment by sabrinaluo** [comment]
我是win7跑完没问题哦，就是二维码傻傻的显示着，让我也傻傻的以为还在跑呢 :laughing:
