### ISSUE TITLE
Python ValueError 报错

### ISSUE THREAD

**Issue by johnny-y-wang** [0x5e/wechat-deleted-friends#79]
Python 2 on Windows & on Mac
不会写python还得麻烦作者帮忙看下

正在登录...
Traceback (most recent call last):
  File "C:\Users\hwang\Desktop\wdf.py", line 517, in <module>
    main()
  File "C:\Users\hwang\Desktop\wdf.py", line 416, in main
    if not webwxinit():
  File "C:\Users\hwang\Desktop\wdf.py", line 239, in webwxinit
    dic = json.loads(data)
  File "C:\Python27\lib\json__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting ':' delimiter: line 23185 column 18 (char 458505)

**Comment by Enumerative** [comment]
我把东西存在C盘也有同样问题，拷到F盘就好了

**Comment by 0x5e** [comment]
现在还有这个问题吗
