### ISSUE TITLE
显示通讯录共0个好友

### ISSUE THREAD

**Issue by nkuflk** [0x5e/wechat-deleted-friends#82]
怎么破

**Comment by CodeBees** [comment]
升级Python版本

**Comment by ghost** [comment]
python3 wdf.py就可以了,不过只能查那个联系人人数，后面就报错了

**Comment by MFC1989** [comment]
python3 wdf.py
本程序的查询结果可能会引起一些心理上的不适,请小心使用...
开始
请使用微信扫描二维码以登录
成功扫描,请在手机上点击确认以登录
正在登录...
通讯录共171位好友
开始查找...
Traceback (most recent call last):
  File "wdf.py", line 543, in <module>
    main()
  File "wdf.py", line 484, in main
    map(lambda x: '#', progress[:(progress_len \* (i + 1)) / group_num]))
TypeError: slice indices must be integers or None or have an **index** method

**Comment by ghost** [comment]
map(lambda x: '#', progress[:(progress_len \* (i + 1)) / group_num]))把progress[:(progress~~那个冒号去掉好像可以了

**Comment by wr573091665** [comment]
楼上的去掉：还是不行，求解

**Comment by ghost** [comment]
搞错了不好意思，我自己是progress[int((progress_len \* (i + 1)) / group_num)])，不知道你的可不可以，把[]里面强制转int好像就可以了

**Comment by wr573091665** [comment]
Hi ，python小白一枚！可以把你的文件发我不 573091665@qq.com

**Comment by fantasylc** [comment]
@wr573091665  除号 / 要换成 //

**Comment by walkerzhao** [comment]
对啊,好友显示怎么为0个了~  试过python2和python3都是这样的
前两天在mac上还挺好,今天换windows和linux都是这个结果, 微信改接口了?

**Comment by apelif** [comment]
ssl._create_default_https_context = ssl._create_unverified_context
把这一句注释掉

**Comment by yswhynot** [comment]
我本来也是……改装anaconda就好了可能还是一些版本什么的问题

**Comment by kusanagii** [comment]
成功扫描,请在手机上点击确认以登录
正在登录...
通讯录共0位好友
开始查找...
？？？？？？？？？？？？？？？？？？？？？？？

**Comment by passioner** [comment]
Ubuntu下尝试了几种情况：1）python wdf.py微信好友数返回为0；2）python3 wdf.py能计算好友数目，但是会返回472行的除法计算问题，尝试了将/改为//，程序能执行，但是提示没有人删我（事先让一个朋友删除我了），强制int类型转换之后，进度条会一直只有一个#号；

**Comment by alpenliebe** [comment]
Ubuntu上换成pyhton 2.7就可以，最好用下anaconda试试

**Comment by passioner** [comment]
现在脚本本身的逻辑问题解决了，但是一直反馈调用太频繁，181的好友，20个一组，每组间隔60s，还是会反馈“操作太频繁，请稍后再试”（把createChatroom里的data打印出来就能看到）

**Comment by mousycoder** [comment]
@apelif  正解

**Comment by 0x5e** [comment]
@apelif @mousycoder 你们的py版本是?

**Comment by apelif** [comment]
@0x5e 2.7.9

**Comment by 0x5e** [comment]
@apelif 方便试一下>= 2.7.10的版本吗

**Comment by wmdsjhjcmd** [comment]
发自我的 iPhone

**Comment by apelif** [comment]
@0x5e 看错了...我用的是2.7.6。在2.7.9下试过了没问题！

**Comment by xiaoxuz** [comment]
python 2.7版本0好友。
python 3版本报错

本程序的查询结果可能会引起一些心理上的不适,请小心使用...
正在获取二维码图片...
请使用微信扫描二维码以登录
成功扫描,请在手机上点击确认以登录
正在登录...
开启心跳线程
通讯录共0位好友
开始查找...

结果汇总完毕,20s后可重试...
---------- 被删除的好友列表(共0人) ----------

## 无

**Comment by 0x5e** [comment]
@xiaoxuz 升至>=2.7.9试试,可能python旧版的ssl处理有问题
